# Generated by Django 6.0.6 on 2026-06-22 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado_general', models.CharField(choices=[('Planificacion', 'Planificación'), ('En progreso', 'En progreso'), ('Completado', 'Completado'), ('Pausado', 'Pausado')], default='Planificacion', max_length=20)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
            },
        ),
        migrations.CreateModel(
            name='ProyectoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='projects.proyecto')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Proyecto',
                'verbose_name_plural': 'Asignaciones de Proyectos',
                'db_table': 'proyecto_usuario',
                'unique_together': {('usuario', 'proyecto', 'rol')},
            },
        ),
    ]
